# -*- coding: utf-8 -*-
"""Pandas_intermediate_part3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16OHtqmBkYQOWaqyO1niTO10rD_LsTe6x
"""

import pandas as pd

data = {
    'Names': ['Alice', 'Bob','Charlie', None, 'Eva'],
    'Age': [25, None, 30, 22, None],
    'Salary': [50000, 40000, 60000, 700000, None],
    'Department': ['HR', 'IT', 'IT', None, 'HR']
}

df = pd.DataFrame(data)
df

df.isnull()

df.isnull().sum()

df_drop_rows = df.dropna()
df_drop_rows

df_drop_columns = df.dropna(axis =1)
df_drop_columns

average_age = df['Age'].mean()
df['Age'] = df['Age'].fillna()

df['Age'] = df['Age'].astype(int)

df

df['Age'] = df['Age'].round().astype(int)
df

df['Salary'] = df['Salary'].fillna(0)
df

df['Names'] = df['Names'].fillna('Unknown')
df

df['Names'] = df['Names'].replace('Unknown', 'Not Provided')
df

df.info()

