# -*- coding: utf-8 -*-
"""Pandas_intermediate_part5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZaH_PExIo306JgLy0ZW1O4QA6qkHXzWI
"""

import pandas as pd

data = {
    "Department": ["IT", "HR", "IT", "Sales", "Sales", "HR", "IT"],
    "Employee": ["A", "B", "C", "D", "E", "F", "G"],
    "Salary": [70000, 50000, 80000, 60000, 65000, 52000, 90000]
}

df = pd.DataFrame(data)
df

df["Salary"].mean()

df["Salary"].sum()

df.groupby("Department")["Salary"].mean()

df.groupby("Department").agg({
    "Salary": ["mean", "min", "max", "sum"]
})

df.groupby("Department").agg({
    "Salary": ["mean", "min", "max", "sum"],
    "Employee": "count"
})

dep_summary = df.groupby("Department").agg({
    "Salary": ["mean", "min", "max", "sum"],
    "Employee": "count"
})
dep_summary

df.groupby("Department")["Salary"].mean().sort_values(ascending = False)

