# -*- coding: utf-8 -*-
"""pandas_intermediate_part2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rATWMTDbrR3qQy2rgBFTi072uFBITGGs
"""

import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Department': ['IT', 'HR', 'IT', 'Finance', 'HR'],
    'Age': [25, 30, 28, 35, 22],
    'Salary': [50000, 45000, 40000, 70000, 48000]
}

df = pd.DataFrame(data)
df

df.loc[df['Department'] == 'IT']

df.loc[(df['Department'] == 'HR') & (df['Age'] > 25)]

df[df['Department'].isin(['IT', 'Finance'])]

df.query('Age > 25 and Salary >= 50000')

df.query("Department == 'IT' ")

