# -*- coding: utf-8 -*-
"""Pandas_intermediate_part4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b1p3FHlLTWDjcoQfBckhqAYiCcd0pA2s
"""

import pandas as pd

data = {
    "Department": ["IT", "HR", "IT", "Sales", "Sales", "HR", "IT"],
    "Employee": ["A", "B", "C", "D", "E", "F", "G"],
    "Salary": [70000, 50000, 80000, 60000, 65000, 52000, 90000]
}

df = pd.DataFrame(data)
df

df.groupby("Department")

df.groupby("Department")["Salary"].mean()

df.groupby("Department")["Employee"].count()

df.groupby("Department").agg({

    "Salary": "mean",
    "Employee": "count"
})

