# -*- coding: utf-8 -*-
"""Pandas Intermediate – Part 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1266LymnRq8a7q-QDjJWUxn1spBL9sAWt
"""

import pandas as pd

data = {
    'Name': ['John', 'Jane', 'Bob', 'Alice','Eva'],
    'Age': [25, 30, 35, 40, 56],
    'Country': ['USA', 'India', 'USA', 'Germany','India'],
    'Salary': [50000, 90000, 70000, 80000, 56000]
}

df = pd.DataFrame(data)
df

df[df['Country'] == 'India']

# & AND , | OR
df[(df['Country']== 'India') & (df['Age'] > 30)]

df[(df['Country'] == 'USA') | (df['Salary'] > 80000)]

df[df['Age'].between(25, 35)]

df[df['Country'].isin(['India', 'Germany'])]

