# -*- coding: utf-8 -*-
"""pd_intermediate_part7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17s2pZBJFEUn1KROO44pYCO3B8zQlVqNd
"""

import pandas as pd

data = {
    "Department": ["HR", "IT", "IT", "Finance", "HR", "Finance", "IT", "HR"],
    "Salary": [40000, 70000, 80000, 65000, 42000, 68000, 90000, 45000],
    "Experience": [2, 5, 7, 4, 3, 6, 8, 4]
}

df = pd.DataFrame(data)
df

avg_salary = df.groupby("Department")["Salary"].mean()
avg_salary

avg_salary.plot(
    kind = "bar",
    title = "Average Salary by Department"
)

df.boxplot(column = "Salary", by = "Department")

df.plot(
    x = "Experience",
    y = "Salary",
    kind = "scatter",
    title = "Experience vs Salary"
)

df.groupby("Department").plot(
    x = "Experience",
    y = "Salary",
    kind = "scatter",
    legend = False
)

