# -*- coding: utf-8 -*-
"""pd_int_part9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GlBqLyqM1VBLV2K446lins5_ng2n8YZd
"""

import pandas as pd

df = pd.read_csv("employee_attrition.csv")

select_cols = [
    "Department",
    "MonthlyIncome",
    "YearsAtCompany",
    "JobSatisfaction",
    "Attrition"
]

df = df[select_cols]
df.head()

df.groupby("Attrition")["MonthlyIncome"].mean()

df.boxplot(column = "MonthlyIncome", by = "Attrition")

df.groupby("Attrition")["YearsAtCompany"].mean()

"""Is Attrition across different depart is different ?

"""

dept_attrition_income = df.groupby([
    "Department", "Attrition"])["MonthlyIncome"].mean()
dept_attrition_income

dept_attrition_income.unstack()

df.groupby("Attrition")["JobSatisfaction"].mean()

df.groupby("Attrition")["JobSatisfaction"].mean().plot(
    kind = "bar",
    title = " Average Job Satisfaction by Attrition"
)

