# -*- coding: utf-8 -*-
"""pd_inter_part6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ixx4OUs6Hj1DPu2pk3eAsSGOFswmZO86
"""

import pandas as pd

data = {
    "Department": ["IT", "HR", "IT", "Sales", "Sales", "HR", "IT"],
    "Employee": ["A", "B", "C", "D", "E", "F", "G"],
    "Salary": [70000, 50000, 80000, 60000, 65000, 52000, 90000]
}

df = pd.DataFrame(data)
df

df.sort_values(by = "Salary", ascending = False)

df.sort_values(by =["Department", "Salary"], ascending = False)

dept_avg = df.groupby("Department")["Salary"].mean()
dept_avg

dept_avg.sort_values(ascending = False)

dept_avg.rank(ascending = False, method = "dense")

dept_summary = (
    df.groupby("Department").agg( Avg_salary = ("Salary","mean"),
                                 Total_salary =("Salary","sum"),
                                 Employees = ("Employee", "count")
)).sort_values(by = "Avg_salary", ascending = False)
dept_summary

dept_summary["Priority"] = dept_summary["Avg_salary"].rank(ascending = False, method = "dense")
dept_summary

