# -*- coding: utf-8 -*-
"""pd_inter_part10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yOBkxggoiFlVphkTLzbVbcrSC3BbhPNc
"""

import pandas as pd

df = pd.read_csv("employees.csv")

df.head()

df.info()

df.describe()

df.columns = df.columns.str.strip().str.lower().str.replace(" ", " _")
df.columns

df["income_per_year"] = df["monthlyincome"] * 12
df["tenure_years"] = df["yearsatcompany"]

high_income_long_tenure = df[(df["income_per_year"] > 80000) &
                             (df["tenure_years"] >= 5)]
high_income_long_tenure

attrition_by_dept = df.groupby("department")["attrition"].value_counts(normalize = True)
attrition_by_dept

dept_summary = df.groupby("department").agg({
    "income_per_year" : ["mean", "max"],
    "jobsatisfaction" : ["mean"]
})
dept_summary

dept_summary.sort_values(
    ("income_per_year", "mean"),
    ascending = False
)

df.isnull().sum()

df.duplicated().sum()

avg_income_by_dept = df.groupby('department')["income_per_year"].mean()
high_attrition_roles = df[df["attrition"] == "Yes"]["jobrole"].value_counts()

df.to_csv("cleaned_employees.csv", index = False)

