# -*- coding: utf-8 -*-
"""Pd_intermediate_part8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HdkqGcGZa94msMuIE8R2-qrfSJLjC3yQ

# [IBM HR Analytics – Employee Attrition & Performance](https://)

Kaggle Link:
👉 https://www.kaggle.com/datasets/pavansubhasht/ibm-hr-analytics-attrition-dataset
"""

import pandas as pd

df = pd.read_csv("Employee_attribute.csv")
df.head()

df.info()

df.isnull().sum().sort_values(ascending = False)

df.select_dtypes(include = "number").columns

df.select_dtypes(include = "object").columns

df["MonthlyIncome"].describe()

df["Attrition"].value_counts()

df = df.drop_duplicates()

select_cols = [
    "Department",
    "JobRole",
    "MonthlyIncome",
    "YearsAtCompany",
    "JobSatisfaction",
    "Attrition"
]
df_clean = df[select_cols]
df_clean.head()

df_clean.groupby("Attrition")["MonthlyIncome"].mean()

