# -*- coding: utf-8 -*-
"""Python_Loops.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16x0oAkXXEs3LTuadCKhKTjfkXXKRuWdu
"""

# Printing numbers from 1 to 5
for i in range(1, 9):
  print(i)

# Looping thriugh each item in a list
fruits = ["apple", "mango","cherry"]

for fruit in fruits:
  print(fruit)

# Printing numbers 1 to 5 using while loop
count = 1

while count <=5:
  print(count)
  count +=1

# stopping the loop when number becomes 5
for num in range(1, 10):
  if num == 5:

    break
  print(num)





# Skipping number 3 using continue
for num in range(1, 6):
  if num == 3 :
    continue
  print(num)

# Nested Loops showing combination of numbers
for i in range(1,3):
  for j in range(1,2):
    print(i,j)