# -*- coding: utf-8 -*-
"""sine_graph.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TtnDHW-wvHEQWg0cdtoQYStRzafDQSMV
"""

# install matplotlib and numpy
!pip install matplotlib numpy

# Importing necessary libraries
import matplotlib.pyplot as plt # matplotlib for plotting graphs
import numpy as np              # Numpy for numerical operations

# Generate 100 , evenly spaced values between 0 and 10(x values)
x = np.linspace(0, 10, 100)

# Generate the y values as the sine of x(creates a sine wave)
y = np.sin(x)

#Create a new figure with a specified size (8 inches wide , 4 inches tall)
plt.figure(figsize=(8,4))

# Plot the sine using the x and y values
# - label: Adds a label to the line for the legend
# - color: Sets the line color to blue
# - linewidth: Sets the line thickness to 2

plt.plot(x, y, label ="Sine Wave", color="blue", linewidth =2)

# Adding a title to the plot
plt.title("Sine Wave Plot")

#Adding a label to the x axis
plt.xlabel("X-Axis")

#Adding a label to the Y axis
plt.ylabel("Y-Axis")

#Display the lengend in the plot (shows the "Sine Wave" label")
plt.legend()

#Show a grid on the plot for better reference
plt.grid(True)

#Display the plot on the screen
plt.show()

