# -*- coding: utf-8 -*-
"""Vortex_animation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YL_r3aU17YwxhOQnkb_LDcwsszmKD9Az
"""

import numpy as np                  # #import numpy for fast math & arrays
import matplotlib.pyplot as plt     # #import matplotlib for visuals
from matplotlib.animation import FuncAnimation  # #for smooth animation

N = 2500                            # #number of particles
W, H = 2*np.pi, 2*np.pi             # #define motion space size
dt = 0.03                           # #speed control of particles

x = np.random.rand(N) * W           # #random x positions
y = np.random.rand(N) * H           # #random y positions

fig, ax = plt.subplots(figsize=(6,6))  # #create drawing canvas
scat = ax.scatter(
    x, y,
    s=2,                            # #particle size
    c=x+y,                          # #color based on position
    cmap="turbo"                    # #high-contrast color map
)

ax.set_xlim(0, W)                   # #limit x axis
ax.set_ylim(0, H)                   # #limit y axis
ax.axis("off")                      # #hide axes for clean look

def update(frame):                  # #animation frame function
    global x, y                     # #use global particle positions

    vx = np.sin(y + frame*0.1)      # #horizontal wave motion
    vy = np.cos(x + frame*0.1)      # #vertical wave motion

    x += vx * dt                    # #update x positions
    y += vy * dt                    # #update y positions

    x %= W                          # #wrap particles horizontally
    y %= H                          # #wrap particles vertically

    scat.set_offsets(np.c_[x, y])   # #move particles on screen
    scat.set_array(x + y)           # #update particle colors
    return scat,                    # #return updated frame

ani = FuncAnimation(
    fig,
    update,
    frames=300,                     # #total animation frames
    interval=30                     # #frame delay (smoothness)
)

plt.show()                          # #display animation