# -*- coding: utf-8 -*-
"""Time Series Forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/134wAFQyYf6MW6RJwDcdfgiP7oSJDGmae

## **Time Series Forecasting: Hotel Booking Demand Prediction**
"""

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("hotel_bookings.csv")

# Create data column
df['arrival_date'] = pd.to_datetime(
   df['arrival_date_year'].astype(str) + '-' +
   df['arrival_date_month'] + '-' +
   df['arrival_date_day_of_month'].astype(str),
   errors = 'coerce'
)

#Group bookings per day

daily_bookings = df.groupby('arrival_date').size()

daily_bookings.head()

plt.figure(figsize =(10,5))
plt.plot(daily_bookings, color = 'blue')
plt.title("Hotel Booking Demand Over Time")
plt.xlabel("Date")
plt.ylabel("Number of bookings")
plt.show()

forcast = daily_bookings.rolling(window = 30).mean()

plt.figure(figsize =(10, 5))
plt.plot(daily_bookings , label = "Actual", alpha = 0.7)
plt.plot(forcast, label = "30-Day Forcast", color = "red")
plt.legend()
plt.title("Booking Demand Forecast (Moving Average)")
plt.show()

