# -*- coding: utf-8 -*-
"""Python_part2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rjk57PdlgjaWGoxxjRfMKzP8DnH-a4G2
"""

#Creat a sample DataFrame
import pandas as pd

data = {
    "Name": ["Alan", "Sara", "John", "Emma", "Mike"],
    "Age": [10, 12, 11, 13, 12],
    "Score": [88, 92, 85, 90, 78]
}
df = pd.DataFrame(data)
df

# Selecting the single column
df["Name"]

# Selecting multiple columns
df[["Name", "Score"]]

df

# Selecting rows by index (iloc)
df.iloc[0]

# selecting multiple rows
df.iloc[1:4]

# selecting rows by Labels(loc)
df.loc[0]

# Condtional Filtering
df[df["Score"]> 90]

# Multiple conditions
df[(df["Score"]> 85) & (df["Age"] > 11)]

df[(df["Score"]> 85) | (df["Age"] > 11)]

# sorting the data
df.sort_values(by = "Score", ascending =False)

# Resetting the index
df.reset_index(drop = True)

df

