# -*- coding: utf-8 -*-
"""Sales_Analysis_Project_using_Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lQ3AtGuo_4aJKOCGR_wbOBGe0q3lPlqx

## Create the Sales Dataset
"""

import pandas as pd

data = {
    'Date': [
        '2024-01-01', '2024-01-02', '2024-01-03',
        '2024-01-04', '2024-01-05', '2024-01-06'
    ],
    'Product': ['Laptop', 'Laptop', 'Phone', 'Phone', 'Tablet', 'Tablet'],
    'Sales': [1200, 1500, 800, 950, 400, 600]
}

df = pd.DataFrame(data)
df

df['Date'] = pd.to_datetime(df['Date'])
df.set_index('Date', inplace = True)
df

df.info()

total_sales = df.groupby('Product')['Sales'].sum()
total_sales

df['Daily_change'] = df['Sales'].diff()
df

df.resample('2D')['Sales'].sum()

best_sales = df['Sales'].idxmax()
best_sales

import matplotlib.pyplot as plt

total_sales.plot(kind = 'bar')
plt.title('Total Sales per Product')
plt.xlabel('Product')
plt.ylabel('Sales')
plt.show()

