# -*- coding: utf-8 -*-
"""Adv_pd_part4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WQp7pJoKmYUKCtDM3uwBNnKNAW6Fx2cj
"""

import pandas as pd
import numpy as np

data = {
    "Employee": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Department": ["HR", "IT", "IT", "Finance", "HR"],
    "Age": ["25", 30, "35", 40, 28],
    "Salary": [50000.0, 70000, 65000.0, 80000, 52000],
    "Experience": [2, 5, 4, 8, 3]
}

df = pd.DataFrame(data)
print(df)

df.info()

df["Age"] = df["Age"].astype("int64")
df["Salary"] = df["Salary"].astype("int64")

df["Department"] = df["Department"].astype("category")

df.info()

["HR", "IT", "IT", "Finance", "HR"]
HE = 1
IT = 2
FINANCE = 3