# -*- coding: utf-8 -*-
"""Adv_pd_part9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HQ4kWuq5jjNTs4me_lqD_L-jXKOVFuTj

## **Pandas Advanced — Part 9**
### Real-World Large Dataset Analysis (How Analysts Actually Work)

## 👉 **Dataset link** :
https://www.kaggle.com/datasets/rishikeshkonapure/hr-analytics-prediction�
"""

import pandas as pd

df = pd.read_csv("HR_Employee_Attrition.csv", low_memory = False)

df

df.shape
df.info(memory_usage="deep")

df["Department"] = df["Department"].astype("category")
df["JobRole"] = df["JobRole"].astype("category")
df["Attrition"] = df["Attrition"].replace({"Yes": 1, "No": 0})

df

high_risk = df.loc[
    (df["Attrition"] == 1) &
    (df["MonthlyIncome"] < 5000) &
    (df["JobSatisfaction"] <= 2)
]

high_risk.head()

summary = (
    df.groupby("Department")
      .agg(
          avg_income=("MonthlyIncome", "mean"),
          attrition_rate=("Attrition", "mean"),
          count=("EmployeeNumber", "count")
      )
      .sort_values("attrition_rate", ascending=False)
)

df["income_trend"] = (
    df.groupby("Department")["MonthlyIncome"]
      .rolling(5)
      .mean()
      .reset_index(level=0, drop=True)
)

df.head(10)

df["LowIncomeFlag"] = (df["MonthlyIncome"] < 4000).astype(int)
df.head()

summary.head()
high_risk.shape

