# -*- coding: utf-8 -*-
"""Adv_pd_part6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Twp1R6koVLs5JhILry4aH6Ma77w_oG1q

## GorupBy Internals & Advanced Patterns
"""

import pandas as pd

data = {
    "Employee": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Department": ["HR", "IT", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 65000, 80000, 52000, 78000],
    "Experience": [2, 5, 4, 8, 3, 7]
}

df = pd.DataFrame(data)
df

df.groupby("Department")["Salary"].mean()

df.groupby("Department")["Salary"].agg(["mean", "min", "max"])

df.groupby(["Department", "Experience"])["Salary"].mean()

df.groupby("Department").agg({
    "Salary": "mean",
    "Experience": "max"
})

#transform()
df["Dept_Avg_Salary"] = df.groupby("Department")["Salary"].transform("mean")
df

df["Above_Avg_Salary"] = df["Salary"] > df["Dept_Avg_Salary"]
df

df.groupby("Department")["Salary"].apply(lambda x: x.mean())

df.groupby("Department")["Salary"].apply(lambda x: x.max()- x.min())

df.groupby("Department")["Salary"].agg(["mean","min", "median", "sum"])

df["Dept_Avg_Salary"] = df.groupby("Department")["Salary"].transform("mean")
df

""" agg() - summary per group
transform() - value per row
apply() - custom logic when nothing else works  """

