# -*- coding: utf-8 -*-
"""Adv_pd_part1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nSjukmtYpEXLdSjTO0752t_DGYr4J5TL

## Pandas Advanced Part 1
"""

import pandas as pd
import numpy as np

raw_data = {
    " Employee Name ": ["Alice ", "bob", "CHARLIE", " David", None],
    "Join Date": ["2022-01-10", "10/02/2022", "2022.03.15", "invalid", "2022-05-01"],
    "Salary($)": ["50000", "60000 ", " seventy thousand", "80000", None],
    "Department ": ["HR", " hr ", "IT", "Finance", "UNKNOWN"],
    "Status": ["Active", "active ", "INACTIVE", "-", ""]
}

df = pd.DataFrame(raw_data)
df

df.columns = (
    df.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("(", "")
    .str.replace(")","")
)
df.columns

df.replace(["-", "", "UNKNOWN", "unknown"], np.nan, inplace = True)
df

df["employee_name"] = df["employee_name"].str.strip().str.title()
df["department"] = df["department"].str.strip().str.upper()
df["status"] = df["status"].str.strip().str.upper()

df[["employee_name", "department", "status"]]

df["join_date"] = pd.to_datetime(df["join_date"], errors = "coerce")
df["join_date"]

df["salary$"] = (df["salary$"].astype(str).str.replace(",", ""))

df["salary$"] = pd.to_numeric(df["salary$"], errors = "coerce")

df["salary$"]

salary_median = df["salary$"].median()
df["salary$"].fillna(salary_median, inplace = True)
df

df["department"].fillna("UNASSIGNED", inplace = True)
df["status"].fillna("UNKNOWN", inplace = True)

df

df["departmnet"] = df["department"].astype("category")
df["status"] = df["status"].astype("category")

df.info()

df.isna().sum()

invalid_salary = df[df["salary$"] < 0]
invalid_salary

df_clean = df.copy()
df_clean

"""### Pandas Advanced Part 2

"""

df.info(memory_usage = 'deep')

df['department'] = df['department'].astype('category')
df['department']

df['salary$'] = pd.to_numeric(df['salary$'], downcast = 'integer')
df['salary$']

df = df.assign(salary_k = df['salary$'] / 1000, is_high_earner = df['salary$'] > 80000)

df['bonus'] = [s * 0.1 for s in df['salary$']]

df['bonus'] = df['salary$'] * 0.1
df['bonus']

high_paid = df.query(" `salary$` > 80000  and  department == 'IT'")

chunks = pd.read_csv("titanic.csv", chunksize = 100000)

for chunk in chunks:
  print(chunk.shape)

df.groupby('department', observed = True)['salary$'].mean()

