# -*- coding: utf-8 -*-
"""Adv_pd_part7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1C2OEsSqc8AaFgjt_s4uBOLPOm4HHFg4n

https://www.kaggle.com/datasets/pavansubhasht/ibm-hr-analytics-attrition-dataset
"""

import pandas as pd

df = pd.read_csv("HR_Employee_Attrition.csv")
df.head()

df.info()

cols = [
    "EmployeeNumber",
    "Department",
    "JobRole",
    "MonthlyIncome",
    "YearsAtCompany",
    "JobSatisfaction",
    "PerformanceRating"
]

df = df[cols]
df.head()

df = df.sort_values(["EmployeeNumber", "YearsAtCompany"])

df["Dept_Avg_Income"] =( df.groupby("Department")["MonthlyIncome"].transform("mean"))

df

df.drop("Dept-Avg_Income",  axis=1)
# df.drop(column ="Dept-Avg_Income")

df = df.drop(columns ="Dept-Avg_Income")

df["Above_Dept_Avg"] = df["MonthlyIncome"] > df["Dept_Avg_Income"]
df.head()

df["Dept_Rank"] = df.groupby("Department")["MonthlyIncome"].rank(ascending=False)
df.head()

df["Cumulative_Income"] = (
    df.groupby("EmployeeNumber")["MonthlyIncome"].cumsum()
)
df.head()

df["Income_Change"] = (
    df.groupby("EmployeeNumber")["MonthlyIncome"]
)
df.head()

