# -*- coding: utf-8 -*-
"""Adv_pd_part9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HQ4kWuq5jjNTs4me_lqD_L-jXKOVFuTj

## **Pandas Advanced — Part 9**
### Real-World Large Dataset Analysis (How Analysts Actually Work)

## 👉 **Dataset link** :
https://www.kaggle.com/datasets/rishikeshkonapure/hr-analytics-prediction�
"""

import streamlit as st
import pandas as pd

# Page Config
st.set_page_config(page_title="HR Analytics Dashboard", layout="wide")
st.title("📊 HR Employee Attrition Analysis")

# 1. Load Data
@st.cache_data
def load_data():
    # Ensure the file path matches your local environment
    df = pd.read_csv("HR_Employee_Attrition.csv", low_memory=False)
    
    # Optimization & Cleaning
    df["Department"] = df["Department"].astype("category")
    df["JobRole"] = df["JobRole"].astype("category")
    df["Attrition_Num"] = df["Attrition"].replace({"Yes": 1, "No": 0})
    return df

df = load_data()

# 2. Sidebar Filters
st.sidebar.header("Filters")
dept_filter = st.sidebar.multiselect("Select Department", 
                                     options=df["Department"].unique(),
                                     default=df["Department"].unique())

# Filter data based on sidebar
filtered_df = df[df["Department"].isin(dept_filter)]

# 3. Key Metrics (KPIs)
col1, col2, col3 = st.columns(3)
col1.metric("Total Employees", len(filtered_df))
col2.metric("Avg Monthly Income", f"${filtered_df['MonthlyIncome'].mean():,.2f}")
col3.metric("Attrition Rate", f"{filtered_df['Attrition_Num'].mean():.2%}")

# 4. High Risk Analysis
st.subheader("⚠️ High Risk Employees")
st.write("Criteria: Attrition = Yes, Income < $5000, Job Satisfaction ≤ 2")

high_risk = filtered_df[
    (filtered_df["Attrition"] == "Yes") & 
    (filtered_df["MonthlyIncome"] < 5000) & 
    (filtered_df["JobSatisfaction"] <= 2)
]

st.dataframe(high_risk, use_container_width=True)
st.info(f"Total High Risk Employees Found: {high_risk.shape[0]}")

# 5. Department Summary Table
st.subheader("🏢 Departmental Trends")
summary = (
    filtered_df.groupby("Department")
      .agg(
          avg_income=("MonthlyIncome", "mean"),
          attrition_rate=("Attrition_Num", "mean"),
          count=("EmployeeNumber", "count")
      )
      .sort_values("attrition_rate", ascending=False)
)
st.table(summary)
