# -*- coding: utf-8 -*-
"""Adv_pd_part8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IrNcRWk740DLrY6Wmo2V7ZeP1wYH1BdO

https://www.kaggle.com/datasets/pavansubhasht/ibm-hr-analytics-attrition-dataset
"""

import pandas as pd

df = pd.read_csv("HR_Employee_Attrition.csv")
df.head()

df["roll_avg"] = df["MonthlyIncome"].rolling(3).mean()
df.head()

df["exp_avg"] = df["MonthlyIncome"].expanding().mean()
df.head()

df["ewm_avg"] = df["MonthlyIncome"].ewm(span = 3).mean()
df.head()

roles = ["Sales Executive", "Research Scientist"]

filtered_df = df[df["JobRole"].isin(roles)]

filtered_df

