# -*- coding: utf-8 -*-
"""Adv_pd_part5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kpTqsyFZMQ37yJKlAwZx9uhtrbyEX1_X

## Advanced Indexing & Query Thinking
"""

import pandas as pd

data = {
    "Employee": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Department": ["HR", "IT", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 65000, 80000, 52000, 78000],
    "Experience": [2, 5, 4, 8, 3, 7]
}

df = pd.DataFrame(data)
df

df.iloc[2]

df.loc[2]

datas = {
    "Employee": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Salary": [50000, 70000, 65000, 80000, 52000, 78000],

}

df = pd.DataFrame(datas, index = [101, 102, 103, 104, 105, 106])
df

df.loc[102]

df.iloc[1]

df.loc[102] # label = 102
df.iloc[102] # Error

df.loc[101: 106]

df.iloc[0:5]

""".iloc = position or index location|  .loc = labels"""

import pandas as pd

data = {
    "Employee": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank"],
    "Department": ["HR", "IT", "Finance", "HR", "IT", "Finance"],
    "Salary": [50000, 70000, 65000, 80000, 52000, 78000],
    "Experience": [2, 5, 4, 8, 3, 7]
}

df = pd.DataFrame(data)
df

df.loc[df["Department"] == "IT"], ["Employee", "Salary"]

df.loc[(df["Department"] == "Finance") & (df["Salary"] > 75000), ["Employee", "Salary"]]

df.loc[df["Department"].isin(["HR", "IT"])]

df.query("Salary > 60000 and Experience >= 5")

min_salary = 60000
df.query("Salary > @min_salary") # @ Allows python variables to use it in the query

df[df["Department"] == "IT"]["Salary"] # Avoid chained indexing

df.loc[df["Department"] == "IT", "Salary"] # Use loc Always prefered

