# -*- coding: utf-8 -*-
"""Advance_pd_part3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EItdkEER_MyWTa6j4IhUOEoDRqjDJVUc
"""

import pandas as pd
import numpy as np

data = {
    "Employee": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Department": ["HR", "IT", "IT", "Finance", "HR"],
    "Salary": [50000, 70000, 65000, 80000, 52000],
    "Experience": [2, 5, 4, 8, 3]
}

df = pd.DataFrame(data)
print(df)

new_salary = []

for salary in df["Salary"]:
  new_salary.append(salary * 1.10)

df["NewSalary_Loop"] = new_salary
df

df["NewSalary_Vectorized"] = df["Salary"] * 1.10
df

from collections import defaultdict
department_bonus = {
    "HR": 1.05,
    "IT": 1.10,
    "Finance": 1.15
}

df["BonusMultiplier"] = df["Department"].map(department_bonus)
df

def salary_category(salary):
  if salary >= 70000:
    return "High"
  elif salary >= 55000:
    return "Medium"
  else:
    return "Low"
df["SalaryCategory"] = df["Salary"].apply(salary_category)
df

df["ExperienceLevel"] = np.where(df["Experience"] >= 5, "Senior", "Junior")
df

6