# -*- coding: utf-8 -*-
"""AI_art_generation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u9V-ci_UY5XqaJ41ckvbTs55zo_XCggK
"""

# install necessary libraries
!pip install -q --upgrade keras-cv
!pip install -q --upgrade keras # keras 3

! pip install matplotlib

import time
import keras_cv
import matplotlib.pyplot as plt
from keras import ops


trending_styles = ["cyberpunk", "oil painting", "digital art", "steampunk"]
selected_style = trending_styles[0]


model = keras_cv.models.StableDiffusion(img_width=512, img_height=512)


prompt = f"A place with a futuristic Park and humans {selected_style} style, neon lights, highly detailed, 8k resolution, cinematic lighting"

print(f"🤩 Generating AI Art based on trending style: {selected_style}.......")


start_time = time.time()
images = model.text_to_image(prompt, batch_size=1)
end_time = time.time()

plt.figure(figsize=(10, 10))
plt.imshow(images[0])
plt.axis("off")
plt.title(f"Generated in {round(end_time - start_time, 2)}s", fontsize=15)
plt.show()

