# -*- coding: utf-8 -*-
"""AI-Based_Text_Sentiment_Visualizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16wc_3KO80g7LeX_mcy2icGYi6ZUlsfZT
"""

# Installations
!pip install transformers
!pip install torch
!pip install matplotlib

# Import Libraries
from transformers import pipeline
import matplotlib.pyplot as plt

# Load sentimental mode
# Load pre-trained senimental analysis model
sentiment_model = pipeline("sentiment-analysis")

# Function to Analyze Sentiment
def analyze_and_visualize(text):
  #Get prediction from the model
  result = sentiment_model(text)[0]
  label = result['label']
  score = result['score']

  print(f"\nPredictd sentiment:{label}")
  print(f"Confidence Score: {score:.2f}")

  # Convert to graph values
  if label =="POSITIVE":
    values = [score, 1 - score]
    labels = ["Positive", "Negative"]

  else:
    values = [1-score, score]
    labels = ["Positive", "Negative"]


  # Plot  a bar chart
  plt.figure(figsize=(7,4))
  plt.bar(labels, values)
  plt.title("Sentiment Confidence")
  plt.ylabel("Score")
  plt.ylim(0, 1)
  plt.show()

user_text = input("Enter a sentence to analyze sentiment: ")
analyze_and_visualize(user_text)

sentences = [
    "I love this product",
    "I am not happy with the service",
    "This is the best day of my life.",
    "I feel terrible today"
]

for s in sentences:
  print("\nAnalyzing:", s)
  analyze_and_visualize(s)

