{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "eaac6267-2e4b-4f0a-bba0-0e2a2b9498f2",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: opencv-python in c:\\anaconda3\\lib\\site-packages (4.11.0.86)Note: you may need to restart the kernel to use updated packages.\n",
      "\n",
      "Requirement already satisfied: numpy in c:\\anaconda3\\lib\\site-packages (1.26.4)\n"
     ]
    }
   ],
   "source": [
    "pip install opencv-python numpy "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "afde4f42-f302-411e-84c1-03de8553eae4",
   "metadata": {},
   "outputs": [],
   "source": [
    "import cv2\n",
    "import numpy as np\n",
    "import math\n",
    "import time\n",
    "\n",
    "# =============================\n",
    "# ENGINE CONFIG\n",
    "# =============================\n",
    "W, H = 900, 900\n",
    "NUM_PARTICLES = 3000\n",
    "DT = 0.15\n",
    "\n",
    "# =============================\n",
    "# PARTICLE STATE\n",
    "# =============================\n",
    "pos = np.random.rand(NUM_PARTICLES, 2) * [W, H]\n",
    "vel = np.zeros((NUM_PARTICLES, 2))\n",
    "colors = np.random.randint(120, 255, (NUM_PARTICLES, 3))\n",
    "\n",
    "# =============================\n",
    "# FLOW FIELD (AI-LIKE MOTION)\n",
    "# =============================\n",
    "def flow_field(x, y, t):\n",
    "    nx = x / W\n",
    "    ny = y / H\n",
    "    angle = (\n",
    "        math.sin(2 * math.pi * nx + t * 0.7) +\n",
    "        math.cos(2 * math.pi * ny + t * 0.9)\n",
    "    )\n",
    "    return np.array([math.cos(angle), math.sin(angle)])\n",
    "\n",
    "# =============================\n",
    "# CANVAS (PERSISTENT MEMORY)\n",
    "# =============================\n",
    "canvas = np.zeros((H, W, 3), dtype=np.uint8)\n",
    "cv2.namedWindow(\"AI Memory Engine\", cv2.WINDOW_NORMAL)\n",
    "\n",
    "t0 = time.time()\n",
    "\n",
    "while True:\n",
    "    t = time.time() - t0\n",
    "\n",
    "    # Fade old memories slowly (trail persistence)\n",
    "    canvas = (canvas * 0.92).astype(np.uint8)\n",
    "\n",
    "    for i in range(NUM_PARTICLES):\n",
    "        x, y = pos[i]\n",
    "\n",
    "        # Flow force\n",
    "        fx, fy = flow_field(x, y, t)\n",
    "\n",
    "        # Update velocity\n",
    "        vel[i] += np.array([fx, fy]) * DT\n",
    "        vel[i] *= 0.96  # damping\n",
    "\n",
    "        # Update position\n",
    "        pos[i] += vel[i]\n",
    "\n",
    "        # Wrap around (infinite space illusion)\n",
    "        pos[i, 0] %= W\n",
    "        pos[i, 1] %= H\n",
    "\n",
    "        ix, iy = int(pos[i, 0]), int(pos[i, 1])\n",
    "\n",
    "        # Draw particle\n",
    "        cv2.circle(\n",
    "            canvas,\n",
    "            (ix, iy),\n",
    "            1,\n",
    "            colors[i].tolist(),\n",
    "            -1\n",
    "        )\n",
    "\n",
    "    # Memory pulse (breathing effect)\n",
    "    pulse = int(40 + 20 * math.sin(t * 2))\n",
    "    cv2.circle(\n",
    "        canvas,\n",
    "        (W // 2, H // 2),\n",
    "        pulse,\n",
    "        (180, 180, 255),\n",
    "        1\n",
    "    )\n",
    "\n",
    "    # Title\n",
    "    cv2.putText(\n",
    "        canvas,\n",
    "        \"AI REMEMBERING 2026\",\n",
    "        (220, 460),\n",
    "        cv2.FONT_HERSHEY_SIMPLEX,\n",
    "        1.1,\n",
    "        (255, 255, 255),\n",
    "        2,\n",
    "        cv2.LINE_AA\n",
    "    )\n",
    "\n",
    "    cv2.imshow(\"AI Memory Engine\", canvas)\n",
    "\n",
    "    if cv2.waitKey(1) & 0xFF == 27:\n",
    "        break\n",
    "\n",
    "cv2.destroyAllWindows() "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4e6ef4e8-cea3-49ba-834d-e88c0f95f446",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "970edf52-6bd3-4024-a15b-0557f97e0a0c",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0bf24a51-3750-498d-9d04-bfeff8a0be9e",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "37d5bd82-c914-4489-874c-4d4f56678615",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1e4eecec-2275-42d9-aa9b-90ec1c9fa4f5",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
