# -*- coding: utf-8 -*-
"""Credit_card_fraud_dectection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16LlBenWCyCIEKhtHVdtkgWZgT6tMeScr
"""

# Credit Card Fraud Dectection

# Imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, roc_auc_score

from sklearn.ensemble import RandomForestClassifier
from imblearn.over_sampling import SMOTE

# Load Dataset
data = pd.read_csv("creditcard.csv")

X = data.drop("Class", axis=1)
y = data["Class"]

print(data["Class"].isna().sum())

data = data.dropna()

X = data.drop("Class", axis=1)
y = data["Class"]

# 3. Train-Test Split
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42, stratify=y)

# 4. Feature Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Handle imbalanced data (SMOTE)
smote = SMOTE(random_state = 42)
X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

# Train Model
model = RandomForestClassifier(
    n_estimators=100,

    random_state=42,
    class_weight = "balanced"

)
model.fit(X_train_resampled, y_train_resampled)

# Predictions
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:,1]

# Evaluation
print("Classification Report:\n")
print(classification_report(y_test, y_pred))

print("ROC AUC Score:", roc_auc_score(y_test, y_prob))

