# -*- coding: utf-8 -*-
"""Customer Segmentation using K-Means (Visual Analytics Project).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/101OJiL8EwZgjNhffvtRnjBC2MsMjifMK

Mall Customer Segmentation Dataset
https://www.kaggle.com/datasets/vjchoudhary7/customer-segmentation-tutorial-in-python
"""

from google.colab import files
files.upload()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("Mall_Customers.csv")
df.head()

X = df[['Annual Income (k$)', 'Spending Score (1-100)']]

from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters = 5, random_state = 42)
df["Cluster"] = kmeans.fit_predict(X)

plt.figure(figsize= (8,6))
sns.scatterplot(
    x = 'Annual Income (k$)',
    y = 'Spending Score (1-100)',
    hue = "Cluster",
    palette = "Set2",
    data = df
)

plt.title("Customer Segmentation using KMeans")
plt.show()

centers = pd.DataFrame(
    kmeans.cluster_centers_,
    columns = ["Annual Income", "Spending Score"]
)
centers

