# -*- coding: utf-8 -*-
"""Daily Temperature Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ukQG0sESlnb9rad5xkKVGq6l4c5GQnSb
"""

# import the required library
import matplotlib.pyplot as plt

# Daily temperatures for a weak ( in Celsius)
days = ["Mon", "Tue", "Wed","Thu", "Fri", "Sat", "Sun"]
temperatures = [22, 24, 29, 23, 25, 20, 21]

plt.figure(figsize=(10,5))  # Set figure size
plt.plot(days, temperatures, marker='o', color='blue', label='Temp (°C)')
plt.title("Daily Temperatures Over a Week")
plt.xlabel("Day")
plt.ylabel("Temperature (°C)")
plt.grid(True)
plt.legend()
plt.show()

# Plot a bar chart for the same data
plt.figure(figsize=(10,5))
plt.bar(days, temperatures, color='orange', alpha=0.7)
plt.title("Daily Temperatures Over a Week (Bar Chart)")
plt.xlabel("Day")
plt.ylabel("Temperature (°C)")
plt.show()

