# -*- coding: utf-8 -*-
"""Resume_screeening_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i5NmbEVy19si4_h5fxiljKDTlBgdsOhL
"""

! pip install nltk scikit-learn # Install required library

import nltk
import re
import numpy as np
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

nltk.download('stopwords')
from nltk.corpus import stopwords

# Test cleaning function (NLP)
def clean_text(text):
  text = text.lower() # convert to lowercase
  text = re.sub(r'[^a-z\s]', '', text) # Remove special characters
  words = text.split()
  words = [w for w in words if w not in stopwords.words('english')]
  return " ".join(words)

# Sample resume

resume_text = """
Python Developer with experience in data analysis , machine learning ,
pandas, numpy, matplotlib, and scikit-learn.
"""

job_description = """
Looking for a python developer skilled in machine learning,
data analysis , and visualization using python libraries .
"""

# Clean the text

resume_clean = clean_text(resume_text)
job_clean = clean_text(job_description)

vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform([resume_clean, job_clean])

# Calculate Similarity (ML logic )
similarity_score = cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:2])
match_percentage = round(similarity_score[0][0] * 100, 2 )

# Output Result
print("Resume-Job Match Score :")
print(f"{match_percentage}% match")

