# -*- coding: utf-8 -*-
"""simple_solar_system.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wm3wMxize9pwtWy3z-riNJC-hNshyyR4
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

# -------------------------------
# Solar System Parameters
# -------------------------------
sun_size = 350
planet_sizes = [60, 45, 40, 35]
orbit_radii = [2, 3.5, 5, 6.5]   # Mercury, Venus, Earth, Mars
speeds = [0.07, 0.05, 0.03, 0.02]  # Orbital speeds
angles = np.array([0, np.pi/2, np.pi, 3*np.pi/2])

# Earth + Moon
earth_index = 2
moon_radius = 0.8
moon_speed = 0.15
moon_angle = 0
moon_size = 20

# -------------------------------
# Figure Setup
# -------------------------------
fig, ax = plt.subplots(figsize=(7,7))

# Make EVERYTHING black
fig.patch.set_facecolor("black")     # Outer background
ax.set_facecolor("black")            # Plot background

ax.set_aspect('equal')
ax.set_xlim(-9, 9)
ax.set_ylim(-9, 9)
ax.axis("off")

# Background stars
np.random.seed(42)
star_x = np.random.uniform(-9, 9, 150)
star_y = np.random.uniform(-9, 9, 150)
ax.scatter(star_x, star_y, color="white", s=3, alpha=0.6)

# Orbit rings
for r, c in zip(orbit_radii, ["gray", "yellow", "cyan", "red"]):
    circle = plt.Circle((0,0), r, color=c, fill=False, linestyle="--", alpha=0.4)
    ax.add_artist(circle)

# Sun
sun = plt.scatter(0, 0, s=sun_size, color="yellow")

# Initial planets
planets = ax.scatter(orbit_radii * np.cos(angles),
                     orbit_radii * np.sin(angles),
                     s=planet_sizes,
                     color=["white", "orange", "blue", "red"])

# Moon placeholder
moon = ax.scatter([], [], s=moon_size, color="lightgray")

# -------------------------------
# Animation Function
# -------------------------------
def update(frame):
    global angles, moon_angle

    # Update planet angles
    angles += speeds
    x = orbit_radii * np.cos(angles)
    y = orbit_radii * np.sin(angles)

    planets.set_offsets(np.c_[x, y])

    # Update moon around Earth
    earth_x, earth_y = x[earth_index], y[earth_index]
    moon_angle += moon_speed

    moon_x = earth_x + moon_radius * np.cos(moon_angle)
    moon_y = earth_y + moon_radius * np.sin(moon_angle)

    moon.set_offsets([moon_x, moon_y])

    return planets, moon

# -------------------------------
# Run Animation
# -------------------------------
animation = FuncAnimation(fig, update, frames=360, interval=30)
HTML(animation.to_jshtml())