# -*- coding: utf-8 -*-
"""SineWaveAnimation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ShXt2AcWGbHNi4psvp8BQiQB44fZWllZ
"""

import matplotlib.pyplot as plt # Import the main plotting library
import numpy as np              # Impor Numpy for efficient numerical operation (like array creation)
from matplotlib.animation import FuncAnimation # Import the core funcaion for creating animation
from IPython.display import HTML  # Import HTML to display the animation correctly in jupyter or colab

# ---Data Preparation ---
x_data = np.arange(0, 2 * np.pi, 0.01) # Create the x-values: an array from 0 to 2*pi (360 degrees) with a step of 0.01)
y_data = np.sin(x_data)                # Calculate the corresponding y-values : the sine of each x-values

# --- Setup the Plot Figure and Axes ---
fig, ax = plt.subplots() # Create a figure (the entire window) and a single set of axes (the plotting area)
line, = ax.plot([], [], lw=2) # Initialize an empty plot line; the comma makes 'line' a single Line2D object

# --- Initialization Function ---
def init():
    # This function is called once at the beginning of the animation
    ax.set_xlim(0, 2 * np.pi) # Set the x-axis limits (0 to 2*pi)
    ax.set_ylim(-1.1, 1.1)    # Set the y-axis limits (slightly more than -1 to 1)
    return line,              # Return the line object(s) that need to be redrawn (required for blit=True)

# --- Animation Update Function ---
def update(frame):
    # This function is called repeatedly for every frame of the animation
    # 'frame' is the current frame number/index provided by FuncAnimation
    # It draws the line up to the current frame index
    line.set_data(x_data[:frame], y_data[:frame]) # Update the line's data to include points from 0 up to 'frame'
    return line,                                  # Return the line object(s) that were modified

# --- Create the Animation Object ---
# len(x_data) is the number of points , which determines the number of frames
anim = FuncAnimation(
    fig, # The figure object to animate
    update, # The animation update function
    init_func=init, # The initialization function
    frames=len(x_data), # The number of frames (points) in the animation
    blit=True # Use blitting to improve performance
)

# ---Display the Animation ----
# Convert the animation object into an HTML /JavaScript representation for display in the notebook
HTML(anim.to_jshtml())

