# -*- coding: utf-8 -*-
"""txt_2_img_ai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ww47C-J_OsbWOubR3pfB-6K9ErjH-N8A
"""

!pip install -q diffusers transformers accelerate torch safetensors

import torch
from diffusers import StableDiffusionPipeline

device = "cuda" if torch.cuda.is_available() else "cpu"

pipe = StableDiffusionPipeline.from_pretrained(
    "runwayml/stable-diffusion-v1-5",
    torch_dtype=torch.float16 if device == "cuda" else torch.float32
).to(device)

prompt = "A futuristic city glowing at night, cyberpunk style"
image = pipe(
    prompt,
    height=512,
    width=512,
    num_inference_steps=25,
    guidance_scale=7.5
).images[0]
image

prompt = "A women Robot in Robotsuit"
image = pipe(
    prompt,
    height=512,
    width=512,
    num_inference_steps=25,
    guidance_scale=7.5
).images[0]
image

