# -*- coding: utf-8 -*-
"""Visualizing ML with t-SNE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LLe7ywVsd9CPUVxuQMAbwRGRk__U19lu
"""

!pip install scikit-learn matplotlib

import matplotlib.pyplot as plt
from sklearn.datasets import load_digits
from sklearn.manifold import TSNE

# Load high dimnetional image data
digits = load_digits()
X = digits.data # 64 features per image
y = digits.target # label (0-9)

# Apply t-SNE (ML Visualization technique)
tsne = TSNE(
    n_components =2,
    perplexity = 30,
    learning_rate = 200,
    random_state = 42
)

X_2d = tsne.fit_transform(X)


# plot result

# Plot result
plt.figure(figsize=(8, 6))
scatter = plt.scatter(
    X_2d[:, 0],
    X_2d[:, 1],
    c=y,
    cmap="tab10",
    s=15
)

plt.colorbar(scatter , label = "Digit label ")
plt.title("t-SNE Visualization of Digit Embeddings")
plt.xlabel("Component 1")
plt.ylabel("Component 2")
plt.show()

