# -*- coding: utf-8 -*-
"""Hotel_Booking_Data_Cleaner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j44tqcsdqvwDaoKk4n42idKai5f24oJc

Hotel Booking Data Cleaner And Prepocessing Tool

https://www.kaggle.com/datasets/jessemostipak/hotel-booking-demand
"""

import pandas as pd

input_file = "hotel_bookings.csv"
df = pd.read_csv(input_file)

print("Dataset Loaded!")
print("Shape:", df.shape)
df.head()

def clean_hotel_data(df):
  print("Starting data cleaning.............")

  print("Standardizing column names.............")
  df.colmns = (
      df.columns
      .str.lower()
      .str.strip()
      .str.replace(" ", "_")

  )

  print("Removing duplicates rows.....")
  before = len(df)
  df = df.drop_duplicates()
  after = len(df)
  print(f" duplicates removed...{before - after}")

  print("Trimming Whitespaces...")
  for col in df.select_dtypes(include = "object").columns:
    df[col] = df[col].astype(str).str.strip()

    print("handing missing values....")

    fill_unknown_cols = ["country", "agent", "company"]

    for col in fill_unknown_cols:
        if col in df.columns:
            df[col] = df[col].replace("nan", pd.NA)
            df[col] = df[col].fillna("Unknown")


    if "children" in df.columns:
      df["children"] = df["children"].replace("0", pd.NA)
      df["children"] = df["children"].fillna(0)
      df["children"] = df["children"].astype(int)
  numeri_cols = df.select_dtypes(include = ["int64", "float64"]).columns

  for col in numeri_cols:
    df[col] = df[col].fillna(df[col].median())
    print("Cleaning completed!")
    print("Final Shape:", df.shape)

    return df

cleaned_df = clean_hotel_data(df)
cleaned_df.head()

output_file = "hotel_bookings_cleaned.csv"
cleaned_df.to_csv(output_file, index = False)

print("Cleaned file saved as :", output_file)

from google.colab import files

files.download(output_file)

print("Missing values after cleaning")
cleaned_df.isna().sum().sort_values(ascending= False).head(10)

