# -*- coding: utf-8 -*-
"""Pandas_part6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zLnL_vPcJvnCiCTduac_zgxKcTJ9Yvnc

# **Time Series Data Analysis with Pandas**
"""

import pandas as pd

data = {
    'Date': [
        '2024-01-01', '2024-01-02', '2024-01-03',
        '2024-01-04', '2024-01-05', '2024-01-06'
    ],
    'Sales': [200, 350, 300, 400, 380, 450]
}

df = pd.DataFrame(data)
df

"""Why Date Conversion Is Important

"""

df.dtypes

"""Convert Date Column to DateTime"""

df['Date'] = pd.to_datetime(df['Date'])
df.dtypes

"""Set date as Index"""

df.set_index('Date', inplace=True)
df

"""Access data Using Dates"""

df.loc['2024-01-03']

"""Add a new Column"""

df['Daily_Growth'] = df['Sales'].diff()
df

df['Precentage_change'] = df['Sales'].pct_change() * 100
df

"""Resample Date"""

df.resample('3D').sum() # group data by 2 days

df

"""Weekly resample"""

df.resample('W').mean()

"""Rolling windows"""

df['Rolling_Avg_3'] = df['Sales'].rolling(window =3).mean()
df

"""Find the best sales day"""

df['Sales'].idxmax()

"""Basic Visualization"""

import matplotlib.pyplot as plt

df['Sales'].plot()
plt.title('Daily Sales Trend')
plt.xlabel('Date')
plt.ylabel('Sales')
plt.show()

