# -*- coding: utf-8 -*-
"""Pandas_part4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ehr6YtUIX9lCdIH-IspiH8hCGXy7GqQx

## **GroupBy & Data Analysis**
"""

import pandas as pd

data = {
    'Product': ['Laptop', 'Laptop', 'Phone', 'Phone', 'Tablet', 'Tablet'],
    'Region': ['Asia', 'Europe', 'Asia', 'Europe', 'Asia', 'Europe'],
    'Sales': [1200, 1500, 800, 950, 400, 600],
    'Quantity': [5, 6, 10, 9, 7, 8]
}

df = pd.DataFrame(data)
df

df.groupby('Product')['Sales'].sum()

df.groupby('Region')['Sales'].mean()

df.groupby(['Product', 'Region'])['Sales'].sum()

df

df.groupby('Product').agg({
    'Sales' : ['sum', 'mean'],
    'Quantity': 'sum'
})

df.groupby('Product').count()

total_sales = df.groupby('Product')['Sales'].sum()
total_sales.reset_index()

df.groupby('Product')['Sales'].sum().sort_values(ascending = False)

df[df['Region'] == "Asia"].groupby('Product')['Sales'].sum()

import matplotlib.pyplot as plt

total_sales = df.groupby('Product')['Sales'].sum()

total_sales.plot(kind ='bar')
plt.title("Total Sales per Product")
plt.xlabel("Product")
plt.ylabel("Sales")
plt.show()

