# -*- coding: utf-8 -*-
"""Pandas_part5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qjdJz66PfIrri8wKLlGYWAGsDbvl7tQf

## **Merge,Left Merge Join & Concat**
"""

import pandas as pd

#Left
customers = pd.DataFrame({
    'CustomerID': [1, 2, 3],
    'Name': ['Alice', 'Bob', 'Charlie']
})

# Right
orders = pd.DataFrame({
    'CustomerID': [1, 2, 4],

    'OrderAmount': [250, 300, 150]
})

pd.merge(customers, orders, on = 'CustomerID')

# Left Merge
pd.merge(customers, orders, on ='CustomerID', how = 'left')

# Concat (Stacking Data)
df1 = pd.DataFrame({'Values': [10, 20]})
df2 = pd.DataFrame({'Values': [30, 40]})

pd.concat([df1, df2])

# Join(index based merge)
customers.set_index("CustomerID").join(
    orders.set_index('CustomerID')
)

