# -*- coding: utf-8 -*-
"""Pandas_part8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D_bh7xb9H7LQ7oCShCbR5vJPs-e8vc-0

## **Pandas Part 8 – Advanced CSV Project (Kaggle)**

## Dataset Kaggle
```
https://www.kaggle.com/datasets/padmapriyatr/netflix-titles
```
"""

import pandas as pd
df = pd.read_csv('netflix_titles.csv')
df.head()

df.info()

df.shape

# check the missing values
df.isna().sum()

df['country'].fillna('Unknown', inplace = True)
df['director'].fillna('Not Available', inplace = True)

df

df.isna().sum()

# Analyze content type
df['type'].value_counts()

df['country'].value_counts().head(10)

import matplotlib.pyplot as plt

df['type'].value_counts().plot(kind = 'bar')
plt.title("Movies vs TV shows on Netflix")
plt.xlabel("Content Type")
plt.ylabel("Count")
plt.show()

recent = df[df['release_year']>= 2018]
recent.head()

recent.shape

df['country'].value_counts().head(10)

yearly = df['release_year'].value_counts().sort_index()
yearly

import matplotlib.pyplot as plt

yearly.plot(kind ='line')
plt.title("Yearly Trend")
plt.xlabel("Year")
plt.ylabel("Count")
plt.show()

recent['type'].value_counts()

"""## Advanced CSV Project - Final Insights and Wrap Up"""

df['listed_in'].value_counts().head(10)

df['listed_in'].value_counts().head(10).plot(kind = 'bar')
plt.title("Top Genres on Netflix")
plt.xlabel('Genres')
plt.ylabel('Count')
plt.show()

df

df['rating'].value_counts()

df['rating'].value_counts().plot(kind = 'bar')
plt.title("Content Rating Distribution")
plt.xlabel("Rating")
plt.ylabel("Count")
plt.show()

df[['type', 'rating']].value_counts().head(10)

