# -*- coding: utf-8 -*-
"""Pandas_part1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X5Cz6a43WBd5fjganEna_R7FiOSRwxdE
"""

import pandas as pd

# What is a pandas Series ?
numbers = pd.Series([10, 20, 30, 40 ,50])
number

# Series with custom Index
marks = pd.Series([85, 90, 78], index = ["Maths", "Science", "English"])
marks

# Accessing the data from Series
marks["Science"]

# What is Dataframe
data = {
    "Name": ["Alan", "Sara", "John"],
    "Age": [10, 12 , 11],
    "Score":[88, 92 ,85]
}
df = pd.DataFrame(data)
df

# Viewing data properly
df.head()

# Basic info of data
df.info()

df.describe()

#Selecting a column
df["Score"]

#Adding a new column
df["Passed"] = df["Score"] >85
df

